github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
github_actions:
  timeout_minutes: 2160
  self_hosted: true
  triggers:
  - push
  - pull_request
provider:
  linux_64: github_actions
