build_platform:
  linux_aarch64: linux_64
c_stdlib_version:
  - "2.28"
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
github_actions:
  self_hosted: true
  timeout_minutes: 1080
  triggers:
  - push
  - pull_request
provider:
  linux_64: github_actions
  linux_aarch64: github_actions
